letsencrypt_email: me@example.com

tljh_admin_user: admin
tljh_admin_pass: MyPassMyPass
tljh_version: 1.0.0
tljh_delete_existing: false
tljh_https: false
tljh_stbarts_dest: /srv/
tljh_prefix: /opt/tljh
tljh_installer_dest: /srv/tljh-installer.py
tljh_installer_url: https://tljh.jupyter.org/bootstrap.py
jupyterhub_config_dest: /opt/tljh/config/jupyterhub_config.d/tljh.py
